name: build-and-test
on:
  push:
    branches: main
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test project
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code
      uses: actions/checkout@v2

    - name: Cache build output
      uses: actions/cache@v2
      with:
        path: |
              ~/.cache/go-build
              ~/go/pkg/mod
        key: ${{ hashFiles('**/go.sum') }}

    - name: Test
      run: CGO_ENABLED=0 go test -coverprofile coverage.txt -failfast -v ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        verbose: true

    - name: Build
      run: CGO_ENABLED=0 go build
